name: Run WhatsApp Bot

on:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Bot
        env:
          FIREBASE_URL: ${{ secrets.Firebase_url }}
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: node index.js
